name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: Brightspace/third-party-actions@actions/checkout
    - uses: Brightspace/setup-node@main
      with:
        node-version: '22.x'
    - name: Build
      run: |
        npm ci
        npm test
        npm run build
    - name: Check dist
      run: |
        git diff --exit-code --ignore-cr-at-eol
